### PR TITLE
Add rollback script

### PR DESCRIPTION
**Pull request by Jell**

### CODE REVIEW

**Comment by Jell** [comment]
> Cool! Do you think we should roll back the worker as well if there is one?

Hum I think the service is usually the critical part that requires a rollback, but rolling back the worker if we have one might not be a bad idea. However I'm not sure I want to write that logic in bash so perhaps we can keep that one for now and consider adding the worker rollback if we implement it in https://github.com/Zimpler/aws-helpers ?

**Comment by Jell** [comment]
> Cool! Do you think we should roll back the worker as well if there is one?

you know what, I can actually do a separate bash script to rollback the worker.

**Comment by hsvallfors** [comment]
By the way, all of this can be done in console, see [here](https://paper.dropbox.com/doc/Deploying-a-new-ECS-app-yFpDt2jn5Q6QKK1up4zBb#:h2=Rollback-deploy). But this is script is probably still good just to make it less manual.

**Comment by Jell** [comment]
> Cool! Do you think we should roll back the worker as well if there is one?

OK we have 2 rollbacks, one for service one for worker, that should be enough

**Comment by Jell** [comment]
> By the way, all of this can be done in console, see [here](https://paper.dropbox.com/doc/Deploying-a-new-ECS-app-yFpDt2jn5Q6QKK1up4zBb#:h2=Rollback-deploy). But this is script is probably still good just to make it less manual.

yeah we did that just now, but then it was a bit stressful to read through the paper & click through while the emergency was out, so I thought it was easy enough to fix a bash script for next time :p

**Comment by Jell** [comment]
ah! turns our we already had that function in https://github.com/Zimpler/aws-helpers... :p

**Pull request merged**
